apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: request-limits-mutator
webhooks:
- clientConfig:
    url: https://us-central1-psyched-freedom-235614.cloudfunctions.net/mutator
  failurePolicy: Fail
  name: us-central1-psyched-freedom-235614.cloudfunctions.net
  namespaceSelector: {}
  rules:
  - apiGroups:
    - apps
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments
    - statefulsets
    - daemonsets