on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

name: Pull Request Code build

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: actions/setup-node
      uses: actions/setup-node@v2.2.0
      with:
        node-version: "14"

    - name: npm install
      run: npm install